# SPDX-License-Identifier: GPL-2.0-only
stats_fs-objs	:= inode.o stats_fs.o
stats_fs-tests-objs	:= stats_fs-tests.o

obj-$(CONFIG_STATS_FS)	+= stats_fs.o
obj-$(CONFIG_STATS_FS_TEST) += stats_fs-tests.o
